### ISSUE TITLE
Make /inventory and /check_self Equipped Items Consistent

### ISSUE THREAD

**Issue by NiklasvonM** [SudoOmbro/pilgram#4]
The /inventory command prints the items using emojis which I find quite easy to read (ui.functions.__get_item_icon).
However, in /check_self, descriptions such as "Head" or "Primary" are used (pilgram.strings.Strings.slots). This is, in my opinion, a bit more difficult to read and not consistent with the previous command.

I suggest also using the __get_item_icon function for /check_self. However, I wasn't sure how to best implement this as this would mix the pilgram and ui module.

If you tell me your architectural preference, I can implement this myself and open a PR.

**Comment by SudoOmbro** [comment]
I refactored the code to move the icons to the Strings file (which makes more sense anyway) and made everything consistent, thanks for the suggestion ;)
